package com.devca.model.dto;

public class PROJECT {

	/* 프로젝트 테이블 */
	private int PROJECT_MEMBER_CODE;
	private int PROJECT_SEQ;
	private String PROJECT_NAME;
	private int PROJECT_YEAR;
	private String PROJECT_ONELINE_EX;
	private String PROJECT_TEAM;
	private int PROJECT_MEMBER;
	private String PROJECT_USE_STACK;
	private String PROJECT_DETAIL;
	private String PROJECT_STORAGE_LINK;
	
	private String PROJECT_WEBSITE;
	private String PROJECT_ANDROID;
	private String PROJECT_IOS;
	public PROJECT() {
		super();
		// TODO Auto-generated constructor stub
	}
	public PROJECT(int pROJECT_MEMBER_CODE, int pROJECT_SEQ, String pROJECT_NAME, int pROJECT_YEAR,
			String pROJECT_ONELINE_EX, String pROJECT_TEAM, int pROJECT_MEMBER, String pROJECT_USE_STACK,
			String pROJECT_DETAIL, String pROJECT_STORAGE_LINK, String pROJECT_WEBSITE, String pROJECT_ANDROID,
			String pROJECT_IOS) {
		super();
		PROJECT_MEMBER_CODE = pROJECT_MEMBER_CODE;
		PROJECT_SEQ = pROJECT_SEQ;
		PROJECT_NAME = pROJECT_NAME;
		PROJECT_YEAR = pROJECT_YEAR;
		PROJECT_ONELINE_EX = pROJECT_ONELINE_EX;
		PROJECT_TEAM = pROJECT_TEAM;
		PROJECT_MEMBER = pROJECT_MEMBER;
		PROJECT_USE_STACK = pROJECT_USE_STACK;
		PROJECT_DETAIL = pROJECT_DETAIL;
		PROJECT_STORAGE_LINK = pROJECT_STORAGE_LINK;
		PROJECT_WEBSITE = pROJECT_WEBSITE;
		PROJECT_ANDROID = pROJECT_ANDROID;
		PROJECT_IOS = pROJECT_IOS;
	}
	public int getPROJECT_MEMBER_CODE() {
		return PROJECT_MEMBER_CODE;
	}
	public void setPROJECT_MEMBER_CODE(int pROJECT_MEMBER_CODE) {
		PROJECT_MEMBER_CODE = pROJECT_MEMBER_CODE;
	}
	public int getPROJECT_SEQ() {
		return PROJECT_SEQ;
	}
	public void setPROJECT_SEQ(int pROJECT_SEQ) {
		PROJECT_SEQ = pROJECT_SEQ;
	}
	public String getPROJECT_NAME() {
		return PROJECT_NAME;
	}
	public void setPROJECT_NAME(String pROJECT_NAME) {
		PROJECT_NAME = pROJECT_NAME;
	}
	public int getPROJECT_YEAR() {
		return PROJECT_YEAR;
	}
	public void setPROJECT_YEAR(int pROJECT_YEAR) {
		PROJECT_YEAR = pROJECT_YEAR;
	}
	public String getPROJECT_ONELINE_EX() {
		return PROJECT_ONELINE_EX;
	}
	public void setPROJECT_ONELINE_EX(String pROJECT_ONELINE_EX) {
		PROJECT_ONELINE_EX = pROJECT_ONELINE_EX;
	}
	public String getPROJECT_TEAM() {
		return PROJECT_TEAM;
	}
	public void setPROJECT_TEAM(String pROJECT_TEAM) {
		PROJECT_TEAM = pROJECT_TEAM;
	}
	public int getPROJECT_MEMBER() {
		return PROJECT_MEMBER;
	}
	public void setPROJECT_MEMBER(int pROJECT_MEMBER) {
		PROJECT_MEMBER = pROJECT_MEMBER;
	}
	public String getPROJECT_USE_STACK() {
		return PROJECT_USE_STACK;
	}
	public void setPROJECT_USE_STACK(String pROJECT_USE_STACK) {
		PROJECT_USE_STACK = pROJECT_USE_STACK;
	}
	public String getPROJECT_DETAIL() {
		return PROJECT_DETAIL;
	}
	public void setPROJECT_DETAIL(String pROJECT_DETAIL) {
		PROJECT_DETAIL = pROJECT_DETAIL;
	}
	public String getPROJECT_STORAGE_LINK() {
		return PROJECT_STORAGE_LINK;
	}
	public void setPROJECT_STORAGE_LINK(String pROJECT_STORAGE_LINK) {
		PROJECT_STORAGE_LINK = pROJECT_STORAGE_LINK;
	}
	public String getPROJECT_WEBSITE() {
		return PROJECT_WEBSITE;
	}
	public void setPROJECT_WEBSITE(String pROJECT_WEBSITE) {
		PROJECT_WEBSITE = pROJECT_WEBSITE;
	}
	public String getPROJECT_ANDROID() {
		return PROJECT_ANDROID;
	}
	public void setPROJECT_ANDROID(String pROJECT_ANDROID) {
		PROJECT_ANDROID = pROJECT_ANDROID;
	}
	public String getPROJECT_IOS() {
		return PROJECT_IOS;
	}
	public void setPROJECT_IOS(String pROJECT_IOS) {
		PROJECT_IOS = pROJECT_IOS;
	}
	
	
}
