--회원번호 시퀀스
DROP SEQUENCE USER_CODE_SEQ;
CREATE SEQUENCE USER_CODE_SEQ
START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999
	NOCYCLE
	NOCACHE;

--회원 테이블
DROP TABLE USERS;

CREATE TABLE USERS(
USER_CODE NUMBER PRIMARY KEY,
USERID VARCHAR2(1000) NOT NULL,
PASSWORD VARCHAR2(1000) NOT NULL,
NAME VARCHAR2(1000) NOT NULL,
CREATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM USERS;

INSERT INTO USERS
VALUES(USER_CODE_SEQ.NEXTVAL,'AAAA','1234', '김철수',SYSDATE);

-----------------------------------------------------------------------------------------------------------------------------

--질문게시판 댓글 시퀀스
DROP SEQUENCE COMMENT_NO_SEQ;

DROP TABLE QNA_COMMENT;

CREATE SEQUENCE COMMENT_NO_SEQ
	START WITH 1
	INCREMENT BY 1
	MAXVALUE 9999
	NOCYCLE
	NOCACHE;

-- 질문게시판 댓글 테이블


CREATE TABLE QNA_COMMENT(
	COMMENT_NO NUMBER NOT NULL, -- 댓글 코드(PK) 시퀀스로 입력
	COMMENT_BOARD_NO NUMBER NOT NULL,
	COMMENT_WRITER VARCHAR2(1000) NOT NULL,
	COMMENT_CONTENT CLOB NOT NULL,			-- 댓글 내용 4GB, 댓글은 내용이 있어야 하므로 NOT NULL
	COMMENT_DATE DATE DEFAULT SYSDATE,	-- 댓글 작성 날짜
	COMMENT_GROUP_NO NUMBER NOT NULL, 			-- 댓글 그룹 (원글의 COMMENT_CODE)
	COMMENT_GROUP_ORDER NUMBER DEFAULT 0 NOT NULL, -- 댓글 그룹 내 순서 (원글의 그룹내 순서는 0순위)
	COMMENT_GROUP_DEPTH NUMBER DEFAULT 0 NOT NULL, -- 원글기준 댓글의 깊이 (원글의DEPTH는 0)
	CONSTRAINT PK_COMMENT_NO PRIMARY KEY(COMMENT_NO),
	CONSTRAINT FK_COMMENT_BOARD_NO_C FOREIGN KEY(COMMENT_BOARD_NO) REFERENCES QNA_BOARD(QNA_BOARD_NO) ON DELETE CASCADE -- 게시글 삭제 시 댓글도 삭제되도록)
);

SELECT * FROM QNA_COMMENT;
SELECT * FROM COMMENTS ORDER BY GROUP_NO ASC, GROUP_ORDER ASC;
--MAIN insertComments query
INSERT INTO COMMENTS(COMMENTNO, COMBOARDNO, COMWRITER, COMCONTENT, COMDATE, COMGROUPNO)
VALUES(COMMENTNOSEQ.NEXTVAL, 21, 'AAA', 'COMMENT', SYSDATE, COMMENTNOSEQ.CURRVAL);
--SUB insertComments query (원글의 GROUP_NO, GRUOP_ORDER+1, GROUP_DEPTH+1)
INSERT INTO COMMENTS(COMMENT_CODE, BOARD_CODE, USER_CODE, GROUP_NO, GROUP_ORDER, GROUP_DEPTH, CONTEXT)
VALUES(SEQ_COMMENTS_COMMENT_CODE.NEXTVAL, 3, 1, 1, 1, 1, 'context');
-- 원글 INSERT 기본 형식
INSERT INTO COMMENTS(COMMENT_CODE, BOARD_CODE, USER_CODE, CONTEXT, CREATE_DATE, GROUP_NO, DEL_YN)
VALUES(SEQ_COMMENTS_COMMENT_CODE.NEXTVAL, 3, 1, 'context', SYSDATE, SEQ_COMMENTS_COMMENT_CODE.CURRVAL, 'N');
-- 대댓글 INSERT 기본 형식
INSERT INTO COMMENTS(COMMENT_CODE, BOARD_CODE, USER_CODE, CONTEXT, CREATE_DATE)
VALUES();

