package com.devca.model.dto.member;

import java.sql.Date;

public class MEMBER_PROFILE {

	private int MEMBER_CODE;

	private String MEMBER_NAME;
	private String MEMBER_EMAIL;
	private String MEMBER_PW;
	private String MEMBER_PHONE;

	private String MEMBER_ENABLED;
	private String MEMBER_ROLE;

	private Date MEMBER_LOGOUT_DATE;
	private Date MEMBER_CREATE_DATE;

	private String MEMBER_PROFILE_IMAGE_NAME;
	private String MEMBER_PROFILE_IMAGE_S_NAME;
	private String MEMBER_PROFILE_PATH;

	private String MEMBER_PROFILE_INTRODUCE;
	private String MEMBER_PROFILE_HOMEPAGE;
	private String MEMBER_PROFILE_AREA;

	private String MEMBER_PROFILE_LATITUDE;
	private String MEMBER_PROFILE_LOGITUDE;

	public MEMBER_PROFILE() {
		super();
		// TODO Auto-generated constructor stub
	}

	public MEMBER_PROFILE(int mEMBER_CODE, String mEMBER_PROFILE_IMAGE_NAME, String mEMBER_PROFILE_IMAGE_S_NAME,
			String mEMBER_PROFILE_PATH, String mEMBER_PROFILE_INTRODUCE, String mEMBER_PROFILE_HOMEPAGE,
			String mEMBER_PROFILE_AREA, String mEMBER_PROFILE_LATITUDE, String mEMBER_PROFILE_LOGITUDE) {
		super();
		MEMBER_CODE = mEMBER_CODE;
		MEMBER_PROFILE_IMAGE_NAME = mEMBER_PROFILE_IMAGE_NAME;
		MEMBER_PROFILE_IMAGE_S_NAME = mEMBER_PROFILE_IMAGE_S_NAME;
		MEMBER_PROFILE_PATH = mEMBER_PROFILE_PATH;
		MEMBER_PROFILE_INTRODUCE = mEMBER_PROFILE_INTRODUCE;
		MEMBER_PROFILE_HOMEPAGE = mEMBER_PROFILE_HOMEPAGE;
		MEMBER_PROFILE_AREA = mEMBER_PROFILE_AREA;
		MEMBER_PROFILE_LATITUDE = mEMBER_PROFILE_LATITUDE;
		MEMBER_PROFILE_LOGITUDE = mEMBER_PROFILE_LOGITUDE;
	}

	public MEMBER_PROFILE(int mEMBER_CODE, String mEMBER_NAME, String mEMBER_EMAIL, String mEMBER_PW,
			String mEMBER_PHONE, String mEMBER_ENABLED, String mEMBER_ROLE, Date mEMBER_LOGOUT_DATE,
			Date mEMBER_CREATE_DATE, String mEMBER_PROFILE_IMAGE_NAME, String mEMBER_PROFILE_IMAGE_S_NAME,
			String mEMBER_PROFILE_PATH, String mEMBER_PROFILE_INTRODUCE, String mEMBER_PROFILE_HOMEPAGE,
			String mEMBER_PROFILE_AREA, String mEMBER_PROFILE_LATITUDE, String mEMBER_PROFILE_LOGITUDE) {
		super();
		MEMBER_CODE = mEMBER_CODE;
		MEMBER_NAME = mEMBER_NAME;
		MEMBER_EMAIL = mEMBER_EMAIL;
		MEMBER_PW = mEMBER_PW;
		MEMBER_PHONE = mEMBER_PHONE;
		MEMBER_ENABLED = mEMBER_ENABLED;
		MEMBER_ROLE = mEMBER_ROLE;
		MEMBER_LOGOUT_DATE = mEMBER_LOGOUT_DATE;
		MEMBER_CREATE_DATE = mEMBER_CREATE_DATE;
		MEMBER_PROFILE_IMAGE_NAME = mEMBER_PROFILE_IMAGE_NAME;
		MEMBER_PROFILE_IMAGE_S_NAME = mEMBER_PROFILE_IMAGE_S_NAME;
		MEMBER_PROFILE_PATH = mEMBER_PROFILE_PATH;
		MEMBER_PROFILE_INTRODUCE = mEMBER_PROFILE_INTRODUCE;
		MEMBER_PROFILE_HOMEPAGE = mEMBER_PROFILE_HOMEPAGE;
		MEMBER_PROFILE_AREA = mEMBER_PROFILE_AREA;
		MEMBER_PROFILE_LATITUDE = mEMBER_PROFILE_LATITUDE;
		MEMBER_PROFILE_LOGITUDE = mEMBER_PROFILE_LOGITUDE;
	}

	public int getMEMBER_CODE() {
		return MEMBER_CODE;
	}

	public void setMEMBER_CODE(int mEMBER_CODE) {
		MEMBER_CODE = mEMBER_CODE;
	}

	public String getMEMBER_NAME() {
		return MEMBER_NAME;
	}

	public void setMEMBER_NAME(String mEMBER_NAME) {
		MEMBER_NAME = mEMBER_NAME;
	}

	public String getMEMBER_EMAIL() {
		return MEMBER_EMAIL;
	}

	public void setMEMBER_EMAIL(String mEMBER_EMAIL) {
		MEMBER_EMAIL = mEMBER_EMAIL;
	}

	public String getMEMBER_PW() {
		return MEMBER_PW;
	}

	public void setMEMBER_PW(String mEMBER_PW) {
		MEMBER_PW = mEMBER_PW;
	}

	public String getMEMBER_PHONE() {
		return MEMBER_PHONE;
	}

	public void setMEMBER_PHONE(String mEMBER_PHONE) {
		MEMBER_PHONE = mEMBER_PHONE;
	}

	public String getMEMBER_ENABLED() {
		return MEMBER_ENABLED;
	}

	public void setMEMBER_ENABLED(String mEMBER_ENABLED) {
		MEMBER_ENABLED = mEMBER_ENABLED;
	}

	public String getMEMBER_ROLE() {
		return MEMBER_ROLE;
	}

	public void setMEMBER_ROLE(String mEMBER_ROLE) {
		MEMBER_ROLE = mEMBER_ROLE;
	}

	public Date getMEMBER_LOGOUT_DATE() {
		return MEMBER_LOGOUT_DATE;
	}

	public void setMEMBER_LOGOUT_DATE(Date mEMBER_LOGOUT_DATE) {
		MEMBER_LOGOUT_DATE = mEMBER_LOGOUT_DATE;
	}

	public Date getMEMBER_CREATE_DATE() {
		return MEMBER_CREATE_DATE;
	}

	public void setMEMBER_CREATE_DATE(Date mEMBER_CREATE_DATE) {
		MEMBER_CREATE_DATE = mEMBER_CREATE_DATE;
	}

	public String getMEMBER_PROFILE_IMAGE_NAME() {
		return MEMBER_PROFILE_IMAGE_NAME;
	}

	public void setMEMBER_PROFILE_IMAGE_NAME(String mEMBER_PROFILE_IMAGE_NAME) {
		MEMBER_PROFILE_IMAGE_NAME = mEMBER_PROFILE_IMAGE_NAME;
	}

	public String getMEMBER_PROFILE_IMAGE_S_NAME() {
		return MEMBER_PROFILE_IMAGE_S_NAME;
	}

	public void setMEMBER_PROFILE_IMAGE_S_NAME(String mEMBER_PROFILE_IMAGE_S_NAME) {
		MEMBER_PROFILE_IMAGE_S_NAME = mEMBER_PROFILE_IMAGE_S_NAME;
	}

	public String getMEMBER_PROFILE_PATH() {
		return MEMBER_PROFILE_PATH;
	}

	public void setMEMBER_PROFILE_PATH(String mEMBER_PROFILE_PATH) {
		MEMBER_PROFILE_PATH = mEMBER_PROFILE_PATH;
	}

	public String getMEMBER_PROFILE_INTRODUCE() {
		return MEMBER_PROFILE_INTRODUCE;
	}

	public void setMEMBER_PROFILE_INTRODUCE(String mEMBER_PROFILE_INTRODUCE) {
		MEMBER_PROFILE_INTRODUCE = mEMBER_PROFILE_INTRODUCE;
	}

	public String getMEMBER_PROFILE_HOMEPAGE() {
		return MEMBER_PROFILE_HOMEPAGE;
	}

	public void setMEMBER_PROFILE_HOMEPAGE(String mEMBER_PROFILE_HOMEPAGE) {
		MEMBER_PROFILE_HOMEPAGE = mEMBER_PROFILE_HOMEPAGE;
	}

	public String getMEMBER_PROFILE_AREA() {
		return MEMBER_PROFILE_AREA;
	}

	public void setMEMBER_PROFILE_AREA(String mEMBER_PROFILE_AREA) {
		MEMBER_PROFILE_AREA = mEMBER_PROFILE_AREA;
	}

	public String getMEMBER_PROFILE_LATITUDE() {
		return MEMBER_PROFILE_LATITUDE;
	}

	public void setMEMBER_PROFILE_LATITUDE(String mEMBER_PROFILE_LATITUDE) {
		MEMBER_PROFILE_LATITUDE = mEMBER_PROFILE_LATITUDE;
	}

	public String getMEMBER_PROFILE_LOGITUDE() {
		return MEMBER_PROFILE_LOGITUDE;
	}

	public void setMEMBER_PROFILE_LOGITUDE(String mEMBER_PROFILE_LOGITUDE) {
		MEMBER_PROFILE_LOGITUDE = mEMBER_PROFILE_LOGITUDE;
	}

	@Override
	public String toString() {
		return "MEMBER_PROFILE [MEMBER_CODE=" + MEMBER_CODE + ", MEMBER_NAME=" + MEMBER_NAME + ", MEMBER_EMAIL="
				+ MEMBER_EMAIL + ", MEMBER_PW=" + MEMBER_PW + ", MEMBER_PHONE=" + MEMBER_PHONE + ", MEMBER_ENABLED="
				+ MEMBER_ENABLED + ", MEMBER_ROLE=" + MEMBER_ROLE + ", MEMBER_LOGOUT_DATE=" + MEMBER_LOGOUT_DATE
				+ ", MEMBER_CREATE_DATE=" + MEMBER_CREATE_DATE + ", MEMBER_PROFILE_IMAGE_NAME="
				+ MEMBER_PROFILE_IMAGE_NAME + ", MEMBER_PROFILE_IMAGE_S_NAME=" + MEMBER_PROFILE_IMAGE_S_NAME
				+ ", MEMBER_PROFILE_PATH=" + MEMBER_PROFILE_PATH + ", MEMBER_PROFILE_INTRODUCE="
				+ MEMBER_PROFILE_INTRODUCE + ", MEMBER_PROFILE_HOMEPAGE=" + MEMBER_PROFILE_HOMEPAGE
				+ ", MEMBER_PROFILE_AREA=" + MEMBER_PROFILE_AREA + ", MEMBER_PROFILE_LATITUDE="
				+ MEMBER_PROFILE_LATITUDE + ", MEMBER_PROFILE_LOGITUDE=" + MEMBER_PROFILE_LOGITUDE + "]";
	}

}
