package com.devca.model.dto.study;

public class STUDY {
	private int STUDY_CODE;
	private int MEMBER_CODE;

	private String STUDY_TITLE;
	private String STUDY_CONTENT;
	private String STUDY_DATE;

	private String STUDY_PLACE_NAME;
	private String STUDY_LOGITUDE;
	private String STUDY_LATITUDE;
	private String STUDY_ADDRESS;

	private int STUDY_PARTICIPANTS;
	private int STUDY_READCOUNT;

	// MEMBER 정보 JOIN COLUMN
	private String MEMBER_NAME;
	private String MEMBER_EMAIL;
	private String MEMBER_PROFILE_IMAGE_S_NAME;

	public STUDY() {
		super();
		// TODO Auto-generated constructor stub
	}

	public STUDY(int sTUDY_CODE, int mEMBER_CODE, String sTUDY_TITLE, String sTUDY_CONTENT, String sTUDY_DATE,
			String sTUDY_LOGITUDE, String sTUDY_LATITUDE, String sTUDY_ADDRESS, int sTUDY_PARTICIPANTS,
			int sTUDY_READCOUNT, String mEMBER_NAME, String mEMBER_EMAIL, String mEMBER_PROFILE_IMAGE_S_NAME) {
		super();
		STUDY_CODE = sTUDY_CODE;
		MEMBER_CODE = mEMBER_CODE;
		STUDY_TITLE = sTUDY_TITLE;
		STUDY_CONTENT = sTUDY_CONTENT;
		STUDY_DATE = sTUDY_DATE;
		STUDY_LOGITUDE = sTUDY_LOGITUDE;
		STUDY_LATITUDE = sTUDY_LATITUDE;
		STUDY_ADDRESS = sTUDY_ADDRESS;
		STUDY_PARTICIPANTS = sTUDY_PARTICIPANTS;
		STUDY_READCOUNT = sTUDY_READCOUNT;
		MEMBER_NAME = mEMBER_NAME;
		MEMBER_EMAIL = mEMBER_EMAIL;
		MEMBER_PROFILE_IMAGE_S_NAME = mEMBER_PROFILE_IMAGE_S_NAME;
	}

	public int getSTUDY_CODE() {
		return STUDY_CODE;
	}

	public STUDY(int sTUDY_CODE, int mEMBER_CODE, String sTUDY_TITLE, String sTUDY_CONTENT, String sTUDY_DATE,
			String sTUDY_PLACE_NAME, String sTUDY_LOGITUDE, String sTUDY_LATITUDE, String sTUDY_ADDRESS,
			int sTUDY_PARTICIPANTS, int sTUDY_READCOUNT, String mEMBER_NAME, String mEMBER_EMAIL,
			String mEMBER_PROFILE_IMAGE_S_NAME) {
		super();
		STUDY_CODE = sTUDY_CODE;
		MEMBER_CODE = mEMBER_CODE;
		STUDY_TITLE = sTUDY_TITLE;
		STUDY_CONTENT = sTUDY_CONTENT;
		STUDY_DATE = sTUDY_DATE;
		STUDY_PLACE_NAME = sTUDY_PLACE_NAME;
		STUDY_LOGITUDE = sTUDY_LOGITUDE;
		STUDY_LATITUDE = sTUDY_LATITUDE;
		STUDY_ADDRESS = sTUDY_ADDRESS;
		STUDY_PARTICIPANTS = sTUDY_PARTICIPANTS;
		STUDY_READCOUNT = sTUDY_READCOUNT;
		MEMBER_NAME = mEMBER_NAME;
		MEMBER_EMAIL = mEMBER_EMAIL;
		MEMBER_PROFILE_IMAGE_S_NAME = mEMBER_PROFILE_IMAGE_S_NAME;
	}

	public int getMEMBER_CODE() {
		return MEMBER_CODE;
	}

	public void setMEMBER_CODE(int mEMBER_CODE) {
		MEMBER_CODE = mEMBER_CODE;
	}

	public String getSTUDY_TITLE() {
		return STUDY_TITLE;
	}

	public void setSTUDY_TITLE(String sTUDY_TITLE) {
		STUDY_TITLE = sTUDY_TITLE;
	}

	public String getSTUDY_CONTENT() {
		return STUDY_CONTENT;
	}

	public void setSTUDY_CONTENT(String sTUDY_CONTENT) {
		STUDY_CONTENT = sTUDY_CONTENT;
	}

	public String getSTUDY_DATE() {
		return STUDY_DATE;
	}

	public void setSTUDY_DATE(String sTUDY_DATE) {
		STUDY_DATE = sTUDY_DATE;
	}

	public String getSTUDY_PLACE_NAME() {
		return STUDY_PLACE_NAME;
	}

	public void setSTUDY_PLACE_NAME(String sTUDY_PLACE_NAME) {
		STUDY_PLACE_NAME = sTUDY_PLACE_NAME;
	}

	public String getSTUDY_LOGITUDE() {
		return STUDY_LOGITUDE;
	}

	public void setSTUDY_LOGITUDE(String sTUDY_LOGITUDE) {
		STUDY_LOGITUDE = sTUDY_LOGITUDE;
	}

	public String getSTUDY_LATITUDE() {
		return STUDY_LATITUDE;
	}

	public void setSTUDY_LATITUDE(String sTUDY_LATITUDE) {
		STUDY_LATITUDE = sTUDY_LATITUDE;
	}

	public String getSTUDY_ADDRESS() {
		return STUDY_ADDRESS;
	}

	public void setSTUDY_ADDRESS(String sTUDY_ADDRESS) {
		STUDY_ADDRESS = sTUDY_ADDRESS;
	}

	public int getSTUDY_PARTICIPANTS() {
		return STUDY_PARTICIPANTS;
	}

	public void setSTUDY_PARTICIPANTS(int sTUDY_PARTICIPANTS) {
		STUDY_PARTICIPANTS = sTUDY_PARTICIPANTS;
	}

	public int getSTUDY_READCOUNT() {
		return STUDY_READCOUNT;
	}

	public void setSTUDY_READCOUNT(int sTUDY_READCOUNT) {
		STUDY_READCOUNT = sTUDY_READCOUNT;
	}

	public String getMEMBER_NAME() {
		return MEMBER_NAME;
	}

	public void setMEMBER_NAME(String mEMBER_NAME) {
		MEMBER_NAME = mEMBER_NAME;
	}

	public String getMEMBER_EMAIL() {
		return MEMBER_EMAIL;
	}

	public void setMEMBER_EMAIL(String mEMBER_EMAIL) {
		MEMBER_EMAIL = mEMBER_EMAIL;
	}

	public String getMEMBER_PROFILE_IMAGE_S_NAME() {
		return MEMBER_PROFILE_IMAGE_S_NAME;
	}

	public void setMEMBER_PROFILE_IMAGE_S_NAME(String mEMBER_PROFILE_IMAGE_S_NAME) {
		MEMBER_PROFILE_IMAGE_S_NAME = mEMBER_PROFILE_IMAGE_S_NAME;
	}

	public void setSTUDY_CODE(int sTUDY_CODE) {
		STUDY_CODE = sTUDY_CODE;
	}

	@Override
	public String toString() {
		return "STUDY [STUDY_CODE=" + STUDY_CODE + ", MEMBER_CODE=" + MEMBER_CODE + ", STUDY_TITLE=" + STUDY_TITLE
				+ ", STUDY_CONTENT=" + STUDY_CONTENT + ", STUDY_DATE=" + STUDY_DATE + ", STUDY_PLACE_NAME="
				+ STUDY_PLACE_NAME + ", STUDY_LOGITUDE=" + STUDY_LOGITUDE + ", STUDY_LATITUDE=" + STUDY_LATITUDE
				+ ", STUDY_ADDRESS=" + STUDY_ADDRESS + ", STUDY_PARTICIPANTS=" + STUDY_PARTICIPANTS
				+ ", STUDY_READCOUNT=" + STUDY_READCOUNT + ", MEMBER_NAME=" + MEMBER_NAME + ", MEMBER_EMAIL="
				+ MEMBER_EMAIL + ", MEMBER_PROFILE_IMAGE_S_NAME=" + MEMBER_PROFILE_IMAGE_S_NAME + "]";
	}

}
